services:
  - type: web
    name: NoHayDosSinTres
    env: docker
    region: frankfurt
    plan: free
    repo: https://github.com/YoelUb/NoHayDosSinTres
    rootDir: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: PORT
        value: "8080"
    autoDeploy: true
