services:
  - name: NoHayDosSinTres
    type: web
    runtime: java
    envVars:
      - key: PORT
        value: 10000
    buildCommand: "mvn clean package"
startCommand: "java -cp target/NoHayDosSinTres.war servidor.Servidor"